[tool.poetry]
name = "final-project"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^6.0.3"
djangorestframework = "^3.17.1"
djangorestframework-simplejwt = "^5.5.1"
django-filter = "^25.2"
django-cors-headers = "^4.9.0"
drf-spectacular = "^0.29.0"
pillow = "^12.1.1"
python-decouple = "^3.8"
psycopg = "^3.2"


[tool.poetry.group.lint.dependencies]
mypy = "^1.19.1"
isort = "^8.0.1"
black = "^26.3.1"
flake8 = "^7.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
